language: java
dist: bionic
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "python3-setuptools"

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk11

before_install:
  - chmod +x gradlew
  - sudo pip3 install -U pip
  - sudo pip3 install -U pyyaml

env:
  - TRAVIS=true

install: ./gradlew assemble --no-daemon
script: travis_wait 20 ./gradlew check --no-daemon

after_success:
  - ./gradlew jacocoTestReport --no-daemon
  - bash <(curl -s https://codecov.io/bash) -F linux

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/