site_name: Gradle-mkdocs-plugin

# Meta tags (placed in header)
site_description: Mkdocs documentation plugin
site_author: Vyacheslav Rusakov
site_url: https://xvik.github.io/gradle-mkdocs-plugin

# Repository (add link to repository on each page)
repo_name: gradle-mkdocs-plugin
repo_url: http://github.com/xvik/gradle-mkdocs-plugin
edit_uri: edit/master/src/doc/docs/

#Copyright (shown at the footer)
copyright: 'Copyright &copy; 2017-2021 Vyacheslav Rusakov'

# Meterial theme
theme: 'material'
extra:
#  palette:
#    primary: 'indigo'
#    accent: 'indigo'

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xvik
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vyarus

plugins:
  - search
  - markdownextradata

# Google Analytics
#google_analytics:
#  - 'UA-111111111-1'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - User guide:
      - Configuration: guide/configuration.md
      - Pip: guide/pip.md
      - Variables: guide/vars.md
      - Multi-version: guide/multi-version.md
      - Publication: guide/publication.md
      - Tasks: guide/tasks.md
      - Themes: guide/theme.md
  - About:
      - Release notes: about/history.md
      - License: about/license.md

dev_addr: 127.0.0.1:3001